# Site settings
title: Discover Warszawa
email: owenthomasclark@me.com
description: "Discover Warszawa is a growing collection of places to visit in Warsaw, Poland."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://discoverwarszawa.com"


# Build settings
markdown: kramdown
permalink: /:title